**creating  numpy arrays**

In [1]:
import numpy as np
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
#2d
b=np.array([[1,2,3],[4,8,9]])
print(b)

[[1 2 3]
 [4 8 9]]


In [5]:
#3d
c=np.array([[1,2],[3,4],[5,7]])
print(c)

[[1 2]
 [3 4]
 [5 7]]


for any other datatype


In [7]:
np.array([1,3,6],dtype=complex)

array([1.+0.j, 3.+0.j, 6.+0.j])

In [6]:
np.array([1,3,6],dtype=float)

array([1., 3., 6.])

arrange func

In [9]:
np.arange(1,39)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38])

In [16]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np.ones((3,4))# USE FOR INITTIZLING

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.random.random((3,4))

array([[0.91945063, 0.58878045, 0.60005298, 0.32297361],
       [0.47201474, 0.24365947, 0.22235015, 0.88221417],
       [0.47689201, 0.13546521, 0.64894475, 0.13532476]])

In [21]:
np.linspace(10,8,70)#GENERATE LINEARLY SEPRABLE POINTS

array([10.        ,  9.97101449,  9.94202899,  9.91304348,  9.88405797,
        9.85507246,  9.82608696,  9.79710145,  9.76811594,  9.73913043,
        9.71014493,  9.68115942,  9.65217391,  9.62318841,  9.5942029 ,
        9.56521739,  9.53623188,  9.50724638,  9.47826087,  9.44927536,
        9.42028986,  9.39130435,  9.36231884,  9.33333333,  9.30434783,
        9.27536232,  9.24637681,  9.2173913 ,  9.1884058 ,  9.15942029,
        9.13043478,  9.10144928,  9.07246377,  9.04347826,  9.01449275,
        8.98550725,  8.95652174,  8.92753623,  8.89855072,  8.86956522,
        8.84057971,  8.8115942 ,  8.7826087 ,  8.75362319,  8.72463768,
        8.69565217,  8.66666667,  8.63768116,  8.60869565,  8.57971014,
        8.55072464,  8.52173913,  8.49275362,  8.46376812,  8.43478261,
        8.4057971 ,  8.37681159,  8.34782609,  8.31884058,  8.28985507,
        8.26086957,  8.23188406,  8.20289855,  8.17391304,  8.14492754,
        8.11594203,  8.08695652,  8.05797101,  8.02898551,  8.  

In [22]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
a3.ndim#tell no of dimension

3

In [27]:
print(a3.shape)

(2, 2, 2)


In [28]:
a3.size

8

In [30]:
a3.itemsize

8

In [32]:
print(a2.dtype)

float64


changing datatype

In [35]:
a3.dtype

dtype('int64')

In [36]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATION

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [42]:
a2>9


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
a2>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [44]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [45]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [46]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [48]:
a1--a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

array function

arithmetic func

In [49]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[11., 27., 60.],
       [30., 25., 70.],
       [49., 89., 13.]])

In [50]:
np.max(a1)

np.float64(89.0)

In [51]:
np.prod(a2)

np.int64(647647525324800)

In [52]:
np.max(a1,axis=0)#for  finding max of each single row use axis 0=col,1=row

array([49., 89., 70.])

In [53]:
np.sum(a1,axis=0)

array([ 90., 141., 143.])

static func


In [55]:
np.mean(a1,axis=1)

array([32.66666667, 41.66666667, 50.33333333])

In [56]:
np.var(a1)

np.float64(647.1358024691358)

In [57]:
np.sin(a1)

array([[-0.99999021,  0.95637593, -0.30481062],
       [-0.98803162, -0.13235175,  0.77389068],
       [-0.95375265,  0.86006941,  0.42016704]])

In [58]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [59]:
np.log(a1)

array([[2.39789527, 3.29583687, 4.09434456],
       [3.40119738, 3.21887582, 4.24849524],
       [3.8918203 , 4.48863637, 2.56494936]])

In [60]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [61]:
np.ceil(np.random.random((2,3))*100)

array([[34.,  3., 19.],
       [69., 48.,  5.]])

INDEXING AND SLICING

In [62]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a2[1,0]

np.int64(4)

In [66]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [67]:
a3[1,0,1]

np.int64(5)

In [68]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a1[2:5:2]

array([2, 4])

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[0,:]

array([0, 1, 2, 3])

In [73]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

iterating

In [75]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [76]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [79]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [80]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [78]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

reshaping

In [81]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [82]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

stacking

In [85]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [86]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [87]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

splitting

In [88]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]